name: Build and Commit CV

on:
  push:
    branches: [ main ]
    paths:
      - "main.tex"

permissions:
  contents: write   # 🔥 중요 (push 권한)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Rename PDF
        run: mv main.pdf cv.pdf

      - name: Commit and Push PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add cv.pdf
          git commit -m "Auto update CV PDF" || echo "No changes to commit"
          git push